server:
  port: 8085
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/learn-db?currentSchema=medical
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
#    initialization-mode: always
#    schema: classpath:/db/schema.sql